### PR TITLE
LDOP-45 docker extensions

### PR DESCRIPTION
**Pull request by ebracho**
Adds a rudimentary extension system for loading new services into ldop and integrating them with the core services. Full documentation is available [here](https://liatrio.atlassian.net/wiki/display/LDOP/Docker+Extensions).

Highlights:
- Extensions live in the *extensions/* subdirectory. We might want to make these submodules in the future.
- Extensions can be loaded into the platform by setting the **EXTENSION** variable in env.config.sh: `EXTENSIONS="artifactory jira confluence"`.
- Each extension defines its own docker-compose file that will be layered on top of the core compose files. The extension's compose file can be used to create new services, create volumes, and add configuration to the core services (like adding an environment variable to jenkins).
- Extensions support integrations with nginx (proxy settings and dashboard configuration) and sensu (adding checks to the sensu-server). In the future, we might also add integrations for jenkins and the other core services.
- Refactored Nexus into an extension and created an Artifactory extension.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Looks good, would like to see some refactoring of extension handling so that certain operations are only run when extensions are specified. That's a lower priority in general and want to work through other PRs and merges before revisiting refactoring in compose.

**Review by ghost — CHANGES_REQUESTED** [review]
Discovered an apparent regression when testing this PR. Specifically, the registry container is in a reboot loop. Additionally, the compose script is stuck continuously checking for the proxy container. Please do additional testing and resolve/report back results.

Steps to reproduce issue:
* compose down anything that might be running
* prune all volumes
* run './adop compose init' on LDOP-45 branch

**Comment by ebracho** [comment]
@liatriojoe The nginx issue is happening because the latest nginx image on dockerhub is still configured to proxy nexus. Building nginx from the [ldop-nginx LDOP-45-docker-extensions branch](https://github.com/liatrio/ldop-nginx/tree/LDOP-45-docker-extensions) will fix the nginx issue.

The registry container restarting is due to the cert not being copied into the registry volume since the init script is stuck before that step.

Developing and testing is a little tricky, since this ticket is spread across three repos (ldop-docker-compose, ldop-nginx, and ldop-sensu). Maybe we should come up with a strategy for developing on multiple repos at the same time. For instance, we could have images on Docker Hub tagged with branch names or ticket ids.

**Comment by ebracho** [comment]
The way extensions are implemented break **adop test** since the test command uses separate volume names from the normal volumes. An easy fix would be to have the test command use the -p option introduced in this branch to run docker-compose with a distinct project name, rather than using the named test* volumes.

**Review by stein321 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
